spring:
  datasource:
    # localhost가 아니라 'search-db'라는 이름을 씁니다 (중요!)
    url: jdbc:postgresql://search-db:5432/search_engine
    username: search_user
    password: search_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 개발용: 테이블 없으면 자동 생성
    show-sql: true
  elasticsearch:
    uris: http://elasticsearch:9200  # k8s 내부 서비스 이름
    connection-timeout: 5s
    socket-timeout: 3s