apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
data:
  # DB 접속 주소가 'localhost'나 'search-db'가 됩니다. (K8s Service 이름)
  DB_URL: "jdbc:postgresql://search-db-svc:5432/search_engine"
  DB_USER: "search_user"
---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  # 실제 비밀번호 (Base64 인코딩은 K8s가 알아서 함)
  DB_PASSWORD: "search_password"
